import images from "./images.json";

// Helpers for the files generated by `npm run images` into public/images/.
// `name` is the file name in images-src/ without its extension.
export const imageInfo = (name) => images[name];

export const imageUrl = (name, format = "webp") =>
  `/images/${name}-${images[name].widths.at(-1)}.${format}`;

export const imageSrcSet = (name, format) =>
  images[name].widths
    .map((w) => `/images/${name}-${w}.${format} ${w}w`)
    .join(", ");
